export const jobData = [
  {
    companyName: 'Photosnap',
    title: 'Senior Frontend Developer',

    new: true,
    featured: true,
    Day: '1d ago',
    type: 'FullTime',
    location: 'USA only',
    img: './photosnap.svg',
    role: 'Frontend',
    level: 'senior',
    tags: ['html', 'css', 'JavaScript'],
  },
  {
    companyName: 'Manage',
    title: 'Junior Frontend Developer',
    new: true,
    featured: true,
    Day: '1d ago',
    type: 'FullTime',
    img: './manage.svg',
    location: 'Remote',
    role: 'Frontend',
    level: 'Junior',
    tags: ['Python'],
  },
  {
    companyName: 'Account',
    new:true,
    title: 'Junior Frontend Developer',
    Day: '2d ago',
    type: 'Part Time',
    img: './account.svg',
    location: 'USA only',
    role: 'Frontend',
    level: 'Junior',
    tags: ['JavaScript'],
  },
  {
    companyName: 'MyHome',
    title: 'Junior Frontend Developer',
    Day: '5d ago',
    type: 'Contract',
    img: './myhome.svg',
    location: 'USA only',
    role: 'Frontend',
    level: 'Junior',
    tags: ['css', 'JavaScript'],
  },
  {
    companyName: ' Loop Studios',
    title: ' Software Engineer',
    Day: '1w ago',
    type: 'Full Time',
    img: './loop-studios.svg',
    location: 'Worldwide',
    role: 'Fullstack',
    level: 'Midweight',
    tags: ['html', 'css', 'JavaScript'],
  },
  {
    companyName: ' FaceIt',
    title: '  Junior Backend Developer',
    Day: '2w ago',
    type: 'Full Time',
    img: './faceit.svg',
    location: 'UK only',
    role: 'Fullstack',
    level: 'Juinor',
    tags: ['ruby'],
  },
  {
    companyName: 'Shortly',
    title: '   Junior Developer',
    Day: '2w ago',
    type: 'Full Time',
    img: './shortly.svg',
    location: 'UK only',
    role: 'Fullstack',
    level: 'Juinor',
    tags: ['html', 'JavaScript'],
  },
  {
    companyName: 'Insure',
    title: '   Junior Frontend Developer',
    Day: '2w ago',
    type: 'Full Time',
    img: './insure.svg',
    location: 'Us only',
    role: 'Frontend',
    level: 'Juinor',
    tags: ['JavaScript'],
  },
  {
    companyName: 'Eyecam Co',
    title: 'Full stack Engineer',
    Day: '3w ago',
    type: 'Full Time',
    img: './insure.svg',
    location: 'Worldwide',
    role: 'Frontend',
    level: 'Midweight',
    tags: ['python', 'JavaScript'],
  },
  {
    companyName: 'The Air Filter Company',
    title: 'Front-end Dev',
    Day: '1mo ago',
    type: 'Part Time',
    img: './the-air-filter-company.svg',
    location: 'Worldwide',
    role: 'Frontend',
    level: 'Juinor',
    tags: ['html', 'css', 'JavaScript'],
  },


];
